### PR TITLE
bundle now uses go embed

### PR DESCRIPTION
**Pull request by taigrr**
See #7 

This PR was created by copying the `bundle.go` file into a new temporary folder, and writing a new `main()` which dumped out the image file to my disk. I've moved that file to the `img/` directory.

Then, the `//go:generate` line was replaced with `//go:embed` as per [the documentation](https://pkg.go.dev/embed).

### CODE REVIEW

**Review by Jacalz — CHANGES_REQUESTED** [review]
Sorry, but this not going to work. We need Go 1.15 support because we are following the latest Debian release which uses that version. Especially important given that our distribution is based on that Debian version.

**Comment by taigrr** [comment]
That's fine. Go 1.16 is in debian testing right now, it has been since November 15 2021 (12 days ago.)

This PR can remain open until it trickles down to Stable.

**Comment by Jacalz** [comment]
Given that we are following the stable release of Debian, I think that’s unfortunately going to be at least two years away :/

**Comment by taigrr** [comment]
I see. Huge bummer. Guess I'll reopen this at some point in the future then.

**Comment by Jacalz** [comment]
> I see. Huge bummer.

Yeah, I know :/

I'm not very happy with it either. I think they just make things worse with not updating it. So much work goes into backporting security patches to years old releases, work that could have been better spent elsewhere. But oh well, it is what it is.

**Comment by andydotxyz** [comment]
Yeah it is a shame, but as Fyne is focused on ease of use for developers and end users alike we have to assume that coders are using their OS standard package manager. Until there is a real reason to break that assumption let's stick with it.

**Comment by andydotxyz** [comment]
As I mentioned on the issue this is technically ok now, but maybe we should hold back until Fyne upstream drops 1.14 in the next release.

**Comment by Jacalz** [comment]
Sounds sensible. We can also target Go 1.17 in that case instead of 1.16

**Comment by Jacalz** [comment]
This should be able to land after you resolve the conflicts :)

**Comment by taigrr** [comment]
Alright, I think the conflicts look resolved to me, let me know if there's anything else

**Comment by Jacalz** [comment]
The tests seem to be failing. Would you mind having a look at them?

**Comment by taigrr** [comment]
@Jacalz I had to update the go.mod to 1.20 and then back to 1.17 to make sure the extra linting rules for 1.20 (which are more strict than 1.17) were applied. Should be good to go

**Review by Jacalz — APPROVED** [review]
I'm happy with this as long as @andydotxyz feel fine about landing it now

**Review by andydotxyz — APPROVED** [review]
Looks good. Sorry for the delay.

**Pull request merged**
