### PR TITLE
fix broken coverage tests

### LINKED ISSUE #13: Code Coverage tests aren't running reliably.
Having just submitted a PR (#11) I wanted to see how the test cases were written. However, I noticed when looking through the logs, that the code coverage report is not actually running, and crashes. This is true for both versions of the check.

image

Running the code locally on my machine, the reason becomes obvious:

```
$ coverage=`go tool cover -func coverage.out | grep total | tr -s '\t' | cut -f 3 | grep -o '[^%]*'`
$ echo $coverage
30.0
```
30.0 isn't an integer, it's a float, which is why bash's -lt operator isn't working.

PR incoming.

image

### PR DESCRIPTION
**Pull request by taigrr**
Fixes #13

### CODE REVIEW

**Comment by taigrr** [comment]
These checks have failed, but they are supposed to fail since I didn't increase test coverage and the current coverage is 21%.

**Comment by andydotxyz** [comment]
25 must have been a copy-paste bug as we use the same checks on multiple repos.
Could you update it to 20, then the tests will pass and we can get it merged? :) thanks

**Comment by taigrr** [comment]
Great, done.

**Review by andydotxyz — APPROVED** [review]
Just for the record the AUTHOR update relates to overall contributions rather than this build script fix I think :)

**Comment by andydotxyz** [comment]
Thanks for this, I will apply the fix to our other repos too :)

**Comment by taigrr** [comment]
Looks like just textedit has the bug now in FyshOS

**Comment by andydotxyz** [comment]
Thanks, I think they are all fixed now. The list was helpful as I noticed a previous fix that was not applied as well

**Comment by taigrr** [comment]
image

**Pull request merged**
